In [1]:
print('Hello')

Hello


### NUMPY

NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy, focusing on arrays and vectorized operations.

In [5]:
pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np

## Create array using numpy
## Create a 1D array

## 1D array
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1)) 
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [ ]:
## Reshaping it to 2D array
arr2 = np.array([1,2,3,4,5])
arr2.reshape((1,5))   ## 1 row 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
## 2D array
arr2 = np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [15]:
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
## Inbuilt function in numpy arrays

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## Attributes of numpy arrays
 
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape) # Output: (2, 3)
print("Number of dimensions:", arr.ndim) # Output: 2
print("Size (number of elements):", arr.size) # Output: 6
print("Data type:", arr.dtype) # Output: int64 (may vary based on platform)
print("Item size (in bytes);", arr.itemsize) # Output: 8 (may vary based on


Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes); 8


In [24]:
## Numpy Vectorized Operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

## Element wise addition
print("Addition:", arr1+arr2)

## Element wise substraction
print("Substraction:", arr1-arr2)

## Element wise multiplication
print("Substraction:", arr1*arr2)

## Element wise division
print("Substraction:", arr1/arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Substraction: [ 10  40  90 160 250]
Substraction: [0.1 0.1 0.1 0.1 0.1]


In [29]:
## Universal Functions (Applied to entire array)

arr = np.array([2,3,4,5,6])

#square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [31]:
## Slicing Operation and Indexing Operation

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
#picking single element from this  array
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [36]:
#Indexing starts with 0
arr[0][0]

np.int64(1)

In [ ]:
arr[1][2]

np.int64(7)

In [ ]:
# 7, 8, 11, 12
arr[1:,2:]  #[1:] -> Select row from 1st index
            #[2:] -> Select column from 2nd index

array([[ 7,  8],
       [11, 12]])

In [42]:
## Modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [43]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
### Statistical Concepts -> Normalization ( mean = 0 and std_dev = 1)
## Change data to have a mean of 0 and std dev 1

### statistical concepts--Normalization
##to have a mean of @ and standard deviation of 1
data= np.array([1, 2, 3, 4, 5])

#Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

#Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

# Output:
#Normalized data: [-1.26491106 -0.63245553 0. 0.63245553 1.26491106]


Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [46]:
data= np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

#Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [ ]:
## Logical Operations

# Find data > 5
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[data > 5]

array([ 6,  7,  8,  9, 10])

In [56]:
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])